DROP VIEW IF EXISTS Countryview;

DROP MATERIALIZED VIEW IF EXISTS Cityview;

CREATE VIEW Countryview AS
SELECT * FROM COUNTRY_T;

CREATE MATERIALIZED VIEW Cityview AS
SELECT * FROM CITY_T;

